import os

from google import genai
from langfuse import get_client, observe

from backends.base import GenericModelBackend


class GeminiBackend(GenericModelBackend):
    """Backend implementation for Google Gemini model.

    Handles real model invocation and token usage reporting for Langfuse.
    Uses the new `google.genai` SDK (replacing the deprecated `google.generativeai`).
    """

    def __init__(
        self,
        model_name: str = "gemini-2.5-flash",
        gemini_api_key: str = "",
    ) -> None:
        """Initialize the Gemini backend.

        Args:
            model_name: The model version name.
            gemini_api_key: Optional API key. Falls back to GEMINI_API_KEY env var.
        """
        super().__init__(model_name)

        # Get Gemini API key from config or environment variable
        self.api_key = gemini_api_key or os.getenv("GEMINI_API_KEY")
        if not self.api_key:
            raise ValueError(
                "Gemini API key is not set. Please provide it in the config "
                "or as an environment variable."
            )

        # Initialize clients
        self.client = genai.Client(api_key=self.api_key)
        self.langfuse = get_client()

    @observe(as_type="generation")
    def generate(self, prompt: str) -> str:
        """Generate content using Gemini and report usage to Langfuse.

        Args:
            prompt: The text prompt to be sent to the Gemini model.

        Returns:
            The text response generated by the model.
        """
        response = self.client.models.generate_content(
            model=self.model_name,
            contents=prompt,
        )
        answer: str = response.text

        # Report token usage to Langfuse dashboard
        if response.usage_metadata:
            self.langfuse.update_current_generation(
                usage_details={
                    "input": response.usage_metadata.prompt_token_count,
                    "output": response.usage_metadata.candidates_token_count,
                    "total": response.usage_metadata.total_token_count,
                },
                model=self.model_name,
            )
        return answer
